### ISSUE TITLE
Hovering over Search icon -> Arrow to Hand

### ISSUE THREAD

**Issue by koustavghosh05** [Voiir/voiir#15]
Hand gesture should come on hovering over Search icon in Homepage.

**Comment by kkb-10** [comment]
Roger that

**Comment by kkb-10** [comment]
Issue fixed. Cursor changing into a pointer when hovering over the search button.

**Comment by koustavghosh05** [comment]
Great job Kirti. Now it's looking more beautiful and meaningful.
