### ISSUE TITLE
Change react app tab name and icon

### ISSUE THREAD

**Issue by void-memories** [Voiir/voiir#29]

**Comment by koustavghosh05** [comment]
@kkb-10 ...please take up this challenge.

**Comment by void-memories** [comment]
![voiir_logo2](https://user-images.githubusercontent.com/46650369/131376434-492f1d46-c4f6-4ea1-a367-a81f01bb53d0.png)
![voiir_logo1](https://user-images.githubusercontent.com/46650369/131376443-11d3aa5c-9c42-4e71-934c-2e7ddce0f7b2.png)

@kkb-10 I've attached the logo for you. Check and use the one that appeals to you the most!

**Comment by kkb-10** [comment]
Roger that

**Comment by kkb-10** [comment]
Fixed the issue in frontend-fix branch. Kindly review it.

**Comment by koustavghosh05** [comment]
Kudos @kkb-10 ...It's looking awesome now.
