### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by void-memories** [Voiir/voiir#32]
first name and surname should not have \n
same goes with city and state

**Comment by koustavghosh05** [comment]
Thanks for the role. Working on it.

**Comment by void-memories** [comment]
Expected completion time?

**Comment by koustavghosh05** [comment]
not much...will just take 5 min :)

**Comment by koustavghosh05** [comment]
It's done. Please check it out.

**Comment by void-memories** [comment]
Good Work @koustavghosh05 💯
