### ISSUE TITLE
Redirect to home page when clicked on voiir logo on search page

### ISSUE THREAD

**Issue by kkb-10** [Voiir/voiir#34]

**Comment by koustavghosh05** [comment]
Thanks for assigning me the task. Working on it.

**Comment by kkb-10** [comment]
Expected such enthusiasm from you. Finish off this work soon manager!

**Comment by koustavghosh05** [comment]
Just a small clarification. By "search page"...do you mean "search-result page"?

**Comment by void-memories** [comment]
Affirmative @koustavghosh05 !

**Comment by koustavghosh05** [comment]
Thanks @void-memories for the clarification.

@kkb-10 ...Enhancement done. Please check it out

**Comment by void-memories** [comment]
Good work bois!
